---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: syr
  name: syr-redis-ssd-claim
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
