---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch  # has to match .spec.template.metadata.labels
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch  # has to match .spec.selector.matchLabels
    spec:
      initContainers:
      # NOTE:
      # This is to fix the permission on the volume
      # By default elasticsearch container is not run as
      # non root user.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      # NOTE:
      # To increase the default vm.max_map_count to 262144
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      # To increase the ulimit
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: increase-the-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers:
        - name: elasticsearch
          # image: justinschuldt/elasticsearch-icu:v7.4.1   # for arm
          image: justinschuldt/elasticsearch-icu:v7.3.2   # for x86
          imagePullPolicy: IfNotPresent
          # resources:
          #   requests:
          #     #  cpu: "3000m"
          #     memory: "4Gi"
          ports:
            - containerPort: 9200
              name: elasticsearch
          env:
            - name: cluster.name
              value: 'es-k8s-gke'
            - name: network.host
              value: '0.0.0.0'
            - name: xpack.license.self_generated.type
              value: basic
            - name: xpack.security.enabled
              value: 'false'
            # - name: xpack.monitoring.collection.enabled
            #   value: 'false'
            # - name: xpack.ml.enabled
            #   value: 'false'
            # - name: ES_JAVA_OPTS
            #   value: "-Xms256m -Xmx256m"
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: password
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: ssd
      # NOTE: You can increase the storage size
      resources:
        requests:
          storage: 8Gi
---